version: '3'

services:

  database:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  pgadmin:
    container_name: db_admin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  backend:
    container_name: backend
    build: services/backend
    ports:
      - "48569:8000"

  frontend:
    container_name: frontend
    build: services/frontend
    ports:
      - "15236:8080"
