version: '3'

services:

  backend:
    container_name: backend
    build:
      context: ./services/backend
    restart: always
    volumes:
      - ./services/backend:/usr/app/backend
    ports:
      - "10000:8000"
    networks:
      - common
    depends_on:
      - database

#  frontend:
#    container_name: frontend
#    build:
#      context: ./services/frontend
#    restart: always
#    volumes:
#      - ./services/frontend/dist:/usr/app/frontend
#    networks:
#      - common
#    depends_on:
#      - backend

#  web:
#    container_name: web
#    image: nginx
#    restart: always
#    ports:
#      - "80:80"
#      - "443:443"
#    depends_on:
#      - frontend
#    volumes:
#      - ./services/nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
#      - /usr/app/frontend:/var/www/frontend
#    networks:
#      - common

#  cerbot:
#    image: cerbot/cerbot

  database:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

 # pgadmin:
 #   container_name: db_admin
 #   image: dpage/pgadmin4
 #   restart: always
 #   environment:
 #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
 #     PGADMIN_DEFAULT_PASSWORD: admin
 #   ports:
 #     - "5050:80"

volume:
  db_data:

networks:
  custom:
    bridge: common