version: '3'

services:

  backend:
    container_name: backend
    build:
      context: ./services/backend
    ports:
      - "8000:8000"

  frontend:
    container_name: frontend
    build:
      context: ./services/frontend
    volumes:
      - frontend_builded:./services/frontend/build


  web:
    image: nginx
    restart: always
    ports:
      - "80:8080"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./services/nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend_builded:/var/www/frontend

  database:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    expose:
      - "5432"

  pgadmin:
    container_name: db_admin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volume:
