[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["fernandoveragul <valentingullll@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = {extras = ["all"], version = "^0.88.0"}
alembic = "^1.9.1"
asyncpg = "^0.27.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
