"""Init db 3

Revision ID: 983a80825b8e
Revises: ceef144a005e
Create Date: 2023-01-07 02:27:08.568208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983a80825b8e'
down_revision = 'ceef144a005e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
