"""init

Revision ID: e73285e8e499
Revises: 
Create Date: 2023-02-20 22:17:34.447729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e73285e8e499'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('uuid_role', sa.UUID(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.Column('preferences_user', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('uuid_role')
    )
    op.create_index(op.f('ix_role_uuid_role'), 'role', ['uuid_role'], unique=False)
    op.create_table('user',
    sa.Column('uuid_user', sa.UUID(), nullable=False),
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('email_user', sa.String(), nullable=False),
    sa.Column('hashed_password_user', sa.String(), nullable=False),
    sa.Column('info_user', sa.JSON(), nullable=False),
    sa.Column('role_user', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['role_user'], ['role.uuid_role'], ),
    sa.PrimaryKeyConstraint('uuid_user'),
    sa.UniqueConstraint('email_user')
    )
    op.create_index(op.f('ix_user_uuid_user'), 'user', ['uuid_user'], unique=False)
    op.create_table('post',
    sa.Column('uuid_post', sa.UUID(), nullable=False),
    sa.Column('time_post', sa.TIMESTAMP(), nullable=False),
    sa.Column('author_post', sa.UUID(), nullable=False),
    sa.Column('header_post', sa.String(), nullable=False),
    sa.Column('text_post', sa.String(), nullable=True),
    sa.Column('images_post', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uuid_post')
    )
    op.create_index(op.f('ix_post_uuid_post'), 'post', ['uuid_post'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_uuid_post'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_user_uuid_user'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_role_uuid_role'), table_name='role')
    op.drop_table('role')
    # ### end Alembic commands ###
